name: Build Fermi

on:
    push:
        tags:
            - "0.*"
            - "1.*"

jobs:
  tsc:
    name: tsc
    runs-on: codeberg-tiny
    steps:
    - uses: actions/checkout@v4
    - name: install node v22
      uses: actions/setup-node@v1
      with:
        node-version: 22
    - name: npm i
      run: npm i
    - name: npm run build
      run: npm run build
    - name: Write desc
      id: desc
      run: echo "NOTES=" >> $FORGEJO_OUTPUT; git tag -n99 --format="%(contents)" >> $FORGEJO_OUTPUT;
    - name: tar it #TODO zip too?
      run: mkdir release; tar -czvf release.tar.gz dist
    - name: echo notes
      run: echo ${{ steps.desc.outputs.NOTES }}
    - uses: actions/forgejo-release@v2.13.4
      with:
        verbose: true
        direction: upload
        url: https://codeberg.org/
        repo: MelodyChat/fermi
        token: ${{ secrets.CODEBERG_TOKEN }}
        tag: ${{ github.ref_name }}
        release-dir: release/
        release-notes: ${{ steps.desc.outputs.NOTES }}

